# Generated by Django 3.0 on 2022-11-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
    ]
